# All values in no of frames
BACKGROUND_COLOR: darkgray
FRAME_RATE: 60
SCREEN_RES: [1920, 1080]
FIX_CROSS_TIME: 30 
NO_TRAINING_TRIALS: [5, 1]
INTRA_BLOCK_TRAINING: 2
NO_BLOCKS: 1
TRAINING_CSI: 10
FIX_CROSS_COLOR: black
QUE_COLOR: darkred
QUE_RADIUS: 20
QUE_SPEED: 2 
QUE_FREQ: 3
QUE_SHIFT: 40
STIM_LETTERS: ←→↑↓
STIM_SIZE: 25
STIM_SHIFT: 600
STIM_TIME: 15
REACTION_TIME: 90
MASK_TIME: 10
REACTION_KEYS: [left, right, up, down]
REACTION_KEYS_SEP: 30
CSI_BAND: [13, 18]
STIM_COLOR: dimgray

