BACKGROUND_COLOR: black
SCREEN_RES: [1920, 1080]
FRAME_RATE: 60

# FIX_CROSS_TIME and STIM_TIME in seconds
FIX_CROSS_COLOR: white
FIX_CROSS_SIZE: 100
FIX_CROSS_TIME: 0.8

STIM_COLOR: white
STIM_SIZE: 150
STIM_TIME: 0.1

# STIM_DELAY in seconds (time between fix cross disappearing and stim showing)
STIM_DELAY: 0.5

INSTRUCTION_SIZE: 30
BREAK_INFO_SIZE: 40
FEEDBACK_SIZE: 70

# NO_TRAINING_TRIALS >= 10
NO_TRAINING_TRIALS: 10
NO_EXPERIMENT_BLOCKS: 3
NO_EXPERIMENT_TRIALS: 20

# REACTION_TIME in frames
REACTION_TIME: 240
REACTION_KEYS: ['left', 'right']
WAIT_KEYS: ['space', 'f7']
EXIT_KEY: f7

# Targets grouped by the same response
TARGET_LETTERS: ['H','K','S','C']
TARGET_GROUPS: [['H','K'],['S','C']]
FLANKERS: ['H','K','S','C','U']
